# Generated by Django 3.0.4 on 2020-07-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200728_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_thumbnail',
            field=models.CharField(default='book_thumbnail', max_length=200),
        ),
    ]
