# Generated by Django 3.0.4 on 2020-07-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_books_book_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Childrens', 'CHILDRENS'), ('Fiction', 'FICTION'), ('NonFiction', 'NONFICTION')], default='NonFiction', max_length=50),
        ),
    ]
