# Generated by Django 3.0.4 on 2020-07-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200730_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Childrens', 'CHILDRENS'), ('Fiction', 'FICTION'), ('NonFiction', 'NONFICTION'), ('Crime', 'CRIME')], default='NonFiction', max_length=50),
        ),
    ]
