# Generated by Django 3.0.4 on 2020-08-01 03:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20200730_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='reads',
            name='month_added',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='ReadingGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(0)])),
                ('reading_goal', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reading_goals',
            },
        ),
    ]
