# Generated by Django 3.0.4 on 2020-07-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200703_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_name', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(default='default_username', max_length=200)),
                ('collection_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_list', to='app.CollectionLists')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterField(
            model_name='reads',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to='app.Users'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_user', to='app.Users'),
        ),
    ]
