# Generated by Django 3.0.4 on 2020-08-06 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20200801_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Upvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_review', to='app.Reviews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upvotes',
            },
        ),
    ]
