# Generated by Django 3.0.4 on 2020-07-05 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20200703_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='collection_list',
        ),
        migrations.AddField(
            model_name='collections',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CollectionLists',
        ),
    ]
