# Generated by Django 3.0.4 on 2020-07-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200710_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(choices=[(1, '1_STAR'), (2, '2_STAR'), (3, '3_STAR'), (4, '4_STAR'), (5, '5_STAR')]),
        ),
    ]
