# Generated by Django 3.0.4 on 2020-07-21 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_extendedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedusers',
            name='email_confirmed',
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
