# Generated by Django 3.0.4 on 2020-07-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200721_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusers',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
    ]
