# Generated by Django 3.0.4 on 2020-07-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200721_0318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUsers',
        ),
    ]
