# Generated by Django 3.0.4 on 2020-07-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200721_0505'),
        ('app', '0018_delete_extendedusers'),
    ]

    operations = [
    ]
