# Generated by Django 3.0.4 on 2020-07-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
