# Generated by Django 3.0.4 on 2020-07-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='verification_code',
            field=models.CharField(default='XYZ', max_length=100),
        ),
    ]
